name: Build

on:
  push:
    branches: [ "master" ]
    
env:
  IMAGE_NAME: jkostov/nodejs-runtime

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_PASSWORD }}
    
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
